server: "192.168.100.150"
username: ""
password: ""
host_name: "LIYUANYUAN"
host_os: "8089D"
host_ip: "10.30.22.17"
PRIMARY_DNS: "114.114.114.114"
dhcp_server: "0.0.0.0"
ror_version: false
nic_name: ""
IS_TEST: true
DEBUG: true
LOG_PATH: "drcom_client.log"
# 十六进制字符串，不带前缀
mac: "b888e3051680"           
CONTROLCHECKSTATUS: "20"       # 对应 b'\x20'
ADAPTERNUM: "01"
KEEP_ALIVE_VERSION: "dc02"
AUTH_VERSION: "0a00"
IPDOG: "01"